// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkWOuApz6zUUNQX181b3zZ53o0z62ssOo',
    appId: '1:820523429031:web:5e49281194214ef33c3f82',
    messagingSenderId: '820523429031',
    projectId: 'surf-comm',
    authDomain: 'surf-comm.firebaseapp.com',
    storageBucket: 'surf-comm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHWc7VlnhZQO9OMO6sOFX1IEQGD9p88c',
    appId: '1:820523429031:android:222fc0a71da2e4f23c3f82',
    messagingSenderId: '820523429031',
    projectId: 'surf-comm',
    storageBucket: 'surf-comm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLR--5wvEnFWeWvDMRago0-2M2LFQ4mU',
    appId: '1:820523429031:ios:69fce0bad6c653a93c3f82',
    messagingSenderId: '820523429031',
    projectId: 'surf-comm',
    storageBucket: 'surf-comm.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSolutionSurf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLR--5wvEnFWeWvDMRago0-2M2LFQ4mU',
    appId: '1:820523429031:ios:69fce0bad6c653a93c3f82',
    messagingSenderId: '820523429031',
    projectId: 'surf-comm',
    storageBucket: 'surf-comm.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceSolutionSurf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkWOuApz6zUUNQX181b3zZ53o0z62ssOo',
    appId: '1:820523429031:web:5e49281194214ef33c3f82',
    messagingSenderId: '820523429031',
    projectId: 'surf-comm',
    authDomain: 'surf-comm.firebaseapp.com',
    storageBucket: 'surf-comm.firebasestorage.app',
  );
}
